services:
  api:
    build:
      context: .
      dockerfile: ProjectDefense.Api/Dockerfile
    ports:
      - "5109:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - JwtSettings__Key=${JWT_KEY}
      - JwtSettings__Issuer=ProjectDefense
      - JwtSettings__Audience=ProjectDefenseUsers
      - CloudinarySettings__CloudName=${CLOUDINARY_CLOUD_NAME}
      - CloudinarySettings__ApiKey=${CLOUDINARY_API_KEY}
      - CloudinarySettings__ApiSecret=${CLOUDINARY_API_SECRET}
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID}
      - Authentication__GitHub__ClientId=${GITHUB_CLIENT_ID}
      - Authentication__GitHub__ClientSecret=${GITHUB_CLIENT_SECRET}
      - EmailSettings__Username=${MAILJET_USERNAME}
      - EmailSettings__Password=${MAILJET_PASSWORD}
      - EmailSettings__SmtpServer=in-v3.mailjet.com
      - EmailSettings__Port=587
      - EmailSettings__From=noreply@bookswapper.cc
      - EmailSettings__AppBaseUrl=https://projectdefense.studentlifehelper.com
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  client:
    build:
      context: ./ProjectDefense.Client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: